name: BUG Test
    
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test on  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-latest, ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            c-compiler: "gcc"
            cxx-compiler: "g++"
          - os: ubuntu-22.04
            c-compiler: "gcc"
            cxx-compiler: "g++"
          - os: macos-latest
            c-compiler: "clang"
            cxx-compiler: "clang++"

    steps:
    - uses: actions/checkout@v2
    - name: Install cppunit  && Install OpenLibm
      if: matrix.os != 'macos-latest' 
      run: |
           sudo apt-get install -y libcppunit-dev
           sudo apt-get install libopenlibm-dev 
    - name: Install openlibm
      if: matrix.os == 'macos-latest' 
      run: brew install openlibm

   
      
    - name: Build and Test on ${{ matrix.os }}
      if: matrix.os == 'ubuntu-20.04'
      run: |
          lsb_release -a

           g++ -std=c++17 bug#55538.cc -o bug#55538
           g++ -std=c++17 Test.cc -lcppunit -o Test
           chmod +x bug#55538
           ./Test
  
           g++ -std=c++17 bug#62332_.cc -o bug#62332_
           ./bug#62332_
          

      
    - name: Build and Test on ${{ matrix.os }}
      if: matrix.os == 'ubuntu-22.04'
      run: |

          lsb_release -a
          gcc --version

          g++ -std=c++17 bug#55538.cc -o bug#55538 -lopenlibm
          ldd bug#55538
          chmod +x bug#55538
          ./bug#55538

          g++ -std=c++2a bug#62212.cc -o bug#62212 -lopenlibm
          ldd bug#62212
          chmod +x bug#62212
          ./bug#62212

          g++ -O1  -std=c++17 bug#62212.cc -o bug#62212
          ./bug#62212

          g++ -std=c++17 bug#62332_.cc -o bug#62332_ -lopenlibm
          ldd bug#62332_
          ./bug#62332_
          g++ -std=c++17 bug#62332_.cc -o bug#62332_ 
          ./bug#62332_

          g++ -std=c++17 bug#62332.cc -o bug#62332 -lopenlibm
          ldd bug#62332
          ./bug#62332
          g++ -std=c++17 bug#62332.cc -o bug#62332
          ./bug#62332



      
    - name: Build and Test on ${{ matrix.os }}
      if: matrix.os == 'macos-latest'
      run: |
            clang --version
            clang++ -stdlib=libc++ bug#55538.cc  -o x
            clang++ -stdlib=libc++ bug#62212.cc  -o v
            ./x
            ./v
            clang++ -stdlib=libc++ bug#55538.cc -o bug#55538  -lopenlibm
            otool -L bug#55538
            ./bug#55538
            clang++ -stdlib=libc++ bug#62212.cc -o bug#62212  -lopenlibm
            otool -L bug#62212
            ./bug#62212
            
            clang++ -stdlib=libc++ bug#62332_.cc  -lopenlibm -o bug#62332_
            otool -L bug#62332_
            ./bug#62332_
            clang++ -stdlib=libc++ bug#62332_.cc  -o bug#62332_
            ./bug#62332_

            clang++ -stdlib=libc++ bug#62332.cc  -lopenlibm -o bug#62332
            otool -L bug#62332
            ./bug#62332
            clang++ -stdlib=libc++ bug#62332.cc  -o bug#62332
            ./bug#62332


            
    